"""Health Score signal engine thresholds (techplan health-score.md)."""

# State thresholds
HEALTH_SCORE_LOW_THRESHOLD = 50
HEALTH_SCORE_CRITICAL_THRESHOLD = 30

# Daily change thresholds
HEALTH_SCORE_DROP_LOW_THRESHOLD = 10
HEALTH_SCORE_DROP_MEDIUM_THRESHOLD = 20
HEALTH_SCORE_DROP_HIGH_THRESHOLD = 30
HEALTH_SCORE_DROP_CRITICAL_THRESHOLD = 40
HEALTH_SCORE_RECOVERY_THRESHOLD = 10

# Baseline / trend
HEALTH_SCORE_BASELINE_LOOKBACK_DAYS = 7
HEALTH_SCORE_LONG_TERM_BASELINE_LOOKBACK_DAYS = 30
HEALTH_SCORE_MINIMUM_DATA_POINTS = 3
HEALTH_SCORE_TREND_MIN_CONSECUTIVE_DAYS = 3
HEALTH_SCORE_TREND_MIN_DEVIATION = 10

# Stable / anomaly / volatility
HEALTH_SCORE_STABLE_MAX_DELTA = 5
HEALTH_SCORE_ANOMALY_MIN_ABSOLUTE_DEVIATION = 20
HEALTH_SCORE_ANOMALY_MIN_RELATIVE_DEVIATION = 0.25
HEALTH_SCORE_VOLATILITY_LOOKBACK_DAYS = 7
HEALTH_SCORE_VOLATILITY_RANGE_THRESHOLD = 30

# Base priorities (higher = more important)
HEALTH_SCORE_PRIORITY = {
    "HEALTH_SCORE_CRITICAL": 1.00,
    "HEALTH_SCORE_ANOMALY": 0.90,
    "HEALTH_SCORE_DROP": 0.85,
    "HEALTH_SCORE_TREND_DOWN": 0.80,
    "HEALTH_SCORE_VOLATILITY_HIGH": 0.70,
    "HEALTH_SCORE_RECOVERY": 0.60,
    "HEALTH_SCORE_TREND_UP": 0.55,
    "HEALTH_SCORE_LOW": 0.50,
    "HEALTH_SCORE_STABLE": 0.20,
}
