"""Sleep signal thresholds."""

# Duration goal reasonableness
SLEEP_GOAL_MIN_H = 5.0
SLEEP_GOAL_MAX_H = 10.0
SLEEP_GOAL_RECOMMENDED_H = 8.0

SLEEP_RECOMMENDED_FLOOR_H = 7.0

# Default bedtime clock when user has no bedtime window
SLEEP_DEFAULT_BEDTIME_LATE_HOUR = 22  # >= 22:00 → late
SLEEP_DEFAULT_BEDTIME_EARLY_HOUR = 6  # < 06:00 → early

# Sleep score → quality buckets
SLEEP_SCORE_VERY_HIGH = 96
SLEEP_SCORE_HIGH = 81
SLEEP_SCORE_OK = 61
SLEEP_SCORE_LOW = 41

# Debt severity ladders (hours short of goal)
SLEEP_DEBT_OK_H = 0.5
SLEEP_DEBT_MILD_H = 1.0
SLEEP_DEBT_MODERATE_H = 2.0

# Trend
SLEEP_TREND_SIGNIFICANT_DIFF_H = 0.5
SLEEP_TREND_WINDOWS_DAYS = (3, 7, 30)

# Aggregation / coverage
SLEEP_SUMMARY_WINDOW_DAYS = 7
SLEEP_BASELINE_WINDOW_DAYS = 14
SLEEP_BASELINE_WINDOW_DAYS_EFFICIENCY = 7  # efficiency is more lifestyle-sensitive → shorter window
SLEEP_MIN_DAYS_FOR_TREND = 2
SLEEP_MIN_DAYS_FOR_BASELINE = 4
SLEEP_MIN_DAYS_FOR_CONSISTENCY = 4

# Consistency (minutes std-dev of bedtime)
SLEEP_BEDTIME_CONSISTENT_STD_MIN = 30
SLEEP_BEDTIME_LATE_CREEP_MIN = 45

# Efficiency
SLEEP_EFFICIENCY_GOOD = 0.85
SLEEP_EFFICIENCY_FAIR = 0.75

# Architecture share targets (of total sleep)
SLEEP_DEEP_SHARE_LOW = 0.13
SLEEP_DEEP_SHARE_OK = 0.18
SLEEP_REM_SHARE_LOW = 0.18
SLEEP_REM_SHARE_OK = 0.22

# Anomaly thresholds
SLEEP_ANOMALY_SHORT_H = 5.0
SLEEP_ANOMALY_LONG_H = 10.0
SLEEP_ANOMALY_LOW_EFFICIENCY = 0.70
SLEEP_ANOMALY_DEEP_SHARE_LOW = 0.10
SLEEP_ANOMALY_REM_SHARE_LOW = 0.15
SLEEP_ANOMALY_LATE_BEDTIME_THRESHOLD_MIN = 0  # phút trễ so với goal_end
SLEEP_ANOMALY_EARLY_WAKE_THRESHOLD_MIN = 0  # phút sớm so với 05:00

# Baseline comparison qualitative bands (hours or score points)
SLEEP_VS_BASELINE_HIGHER_H = 0.3
SLEEP_VS_BASELINE_LOWER_H = -0.3
SLEEP_VS_BASELINE_HIGHER_SCORE = 5
SLEEP_VS_BASELINE_LOWER_SCORE = -5

# Baseline / trend bands for sleep efficiency (0–1 scale)
SLEEP_VS_BASELINE_HIGHER_EFF = 0.02
SLEEP_VS_BASELINE_LOWER_EFF = -0.02
SLEEP_TREND_SIGNIFICANT_DIFF_EFF = 0.02

# Overall score weights (0–100)
SLEEP_OVERALL_WEIGHT_DURATION = 0.35
SLEEP_OVERALL_WEIGHT_EFFICIENCY = 0.20
SLEEP_OVERALL_WEIGHT_SCORE = 0.25
SLEEP_OVERALL_WEIGHT_DEBT = 0.20

# Stage estimate ratios when API omits stages
SLEEP_ESTIMATE_DEEP_RATIO = 0.18
SLEEP_ESTIMATE_REM_RATIO = 0.22
SLEEP_ESTIMATE_LIGHT_RATIO = 0.55

# Guardrail alias used by HealthInsightProcessor sanity checks
SLEEP_SEVERE_LOW_HOURS = 4.0
